// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGuBFq0TGokWXEhFqIRD993Kh7iYZwAE',
    appId: '1:791348480907:android:251254276b59ddadd6bd8e',
    messagingSenderId: '791348480907',
    projectId: 'mynotesapp-c94ef',
    storageBucket: 'mynotesapp-c94ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPse_qkmLlC8Ljs7NK_TQhK14arZpKQOE',
    appId: '1:791348480907:ios:ecacfe920638f074d6bd8e',
    messagingSenderId: '791348480907',
    projectId: 'mynotesapp-c94ef',
    storageBucket: 'mynotesapp-c94ef.firebasestorage.app',
    iosBundleId: 'com.example.mytaskapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1okgyFDgjlS2vjiLhhrU3J38i7-tiaLQ',
    appId: '1:791348480907:web:c3b47ac021c8a261d6bd8e',
    messagingSenderId: '791348480907',
    projectId: 'mynotesapp-c94ef',
    authDomain: 'mynotesapp-c94ef.firebaseapp.com',
    storageBucket: 'mynotesapp-c94ef.firebasestorage.app',
    measurementId: 'G-WQ42DQWPSV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPse_qkmLlC8Ljs7NK_TQhK14arZpKQOE',
    appId: '1:791348480907:ios:ecacfe920638f074d6bd8e',
    messagingSenderId: '791348480907',
    projectId: 'mynotesapp-c94ef',
    storageBucket: 'mynotesapp-c94ef.firebasestorage.app',
    iosBundleId: 'com.example.mytaskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1okgyFDgjlS2vjiLhhrU3J38i7-tiaLQ',
    appId: '1:791348480907:web:21f2171984b6a7e2d6bd8e',
    messagingSenderId: '791348480907',
    projectId: 'mynotesapp-c94ef',
    authDomain: 'mynotesapp-c94ef.firebaseapp.com',
    storageBucket: 'mynotesapp-c94ef.firebasestorage.app',
    measurementId: 'G-T98DQTRR0T',
  );

}